# This is a basic workflow to help you get started with Actions

name: Tests on production branches

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        run: docker build -t mrs-tarquin:latest .

      - name: run tests
        run: docker run --mount type=bind,source=$(pwd),target=/mrs mrs-tarquin pytest --junitxml=cov/pytest.xml  --continue-on-collection-errors tests/ | tee cov/pytest-coverage.txt ; echo $?

      - name: Pytest coverage
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./cov/pytest-coverage.txt
          junitxml-path: ./cov/pytest.xml