# This is a basic workflow to help you get started with Actions

name: Test MRS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: setup virtual environment
        run: |
          python3.6 -m venv env
          source ./env/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
          python3.6 -m pip install --upgrade pip

      - name: Install system requirements
        run: |
          source ./env/bin/activate
          sudo apt-get update
          sudo apt-get install default-libmysqlclient-dev poppler-utils wget dcmtk gnuplot libcairo2-dev libtiff5-dev libjpeg62 zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk ghostscript -y

      - name: install python packages
        run: |
          source ./env/bin/activate
          python3.6 -m pip install pytest suspect pytest-cov colorlog pymsteams appdirs pynetdicom
          python3.6 -m pip install git+https://${{ secrets.dicomserver_uname }}:${{ secrets.dicomserver_pw }}@bitbucket.org/gsttmri/dicomserver.git@0.12.4.1
          which dicomserver


      - name: Install Tarquin
        run: |
          source ./env/bin/activate
          mkdir ../tarquin_folder && wget -O tarquin.tar.gz https://sourceforge.net/projects/tarquin/files/TARQUIN_4.3.11/TARQUIN_Linux_4.3.11.tar.gz/download && tar -xzf tarquin.tar.gz -C ../tarquin_folder && rm tarquin.tar.gz
          mv ../tarquin_folder/TARQUIN_Linux_4.3.11_RC/tarquin /usr/local/bin/tarquin && ln -s /usr/bin/gnuplot /usr/local/bin/gnuplot

      - name: print env info
        run: |
          python3 -c "import sys; print('python3 sys.prefix: ' + sys.prefix)"
          python3 -c "import sys; print('python3 sys.base_prefix: ' + sys.base_prefix)"
          source ./env/bin/activate
          python3 -c "import sys; print('post activate python3 sys.prefix' + sys.prefix)"
          python3 -c "import sys; print('post activate python3 sys.base_prefix: ' + sys.base_prefix)"

      - name: Run MRS tests
        run: |
          source ./env/bin/activate
          python3.6 -m pytest --continue-on-collection-errors tests/

#          # Create virtual environmet & activate
#          - dicomserver/bin/create_venv.sh ../venv
#          - source ../venv/bin/activate
#          # Install requirements
#          - apt-get update && apt-get install default-libmysqlclient-dev -y
#          - ../venv/bin/pip3 install --upgrade pip
#          - ../venv/bin/pip3 install -r requirements.txt
#          - apt-get update && apt-get install poppler-utils wget dcmtk gnuplot libcairo2-dev libtiff5-dev libjpeg62 zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk ghostscript -y
#          # Install tarquin, move relevant packages into path
#          - mkdir ../tarquin_folder && wget -O tarquin.tar.gz https://sourceforge.net/projects/tarquin/files/TARQUIN_4.3.11/TARQUIN_Linux_4.3.11.tar.gz/download && tar -xzf tarquin.tar.gz -C ../tarquin_folder && rm tarquin.tar.gz
#          - mv ../tarquin_folder/TARQUIN_Linux_4.3.11_RC/tarquin /usr/local/bin/tarquin && ln -s /usr/bin/gnuplot /usr/local/bin/gnuplot
#          # Run tests
#          - pytest --continue-on-collection-errors dicomserver_tests/
